/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PettaInventory;

/**
 *
 * @author MasterPaulo
 */
public class BuyMenu extends javax.swing.JFrame {
    private InventoryItem item2Buy;
    private double TotalPrice =0.0;
    private double change = 0.0;
    private double cash = 0.0;
    private int qua;
    public BuyMenu(InventoryItem item2Buy) {
        super("Buying - " + item2Buy.getItemName());
        this.item2Buy = item2Buy;
        initComponents();
        quantitySpinner.setModel( new javax.swing.SpinnerNumberModel(0,0,Integer.MAX_VALUE,1));
        loadInfo();
    }

    public final void loadInfo(){
        String address = "/PettaInventory/images/";
        if(item2Buy.getItemCode()==0)
            address+="processors/";
        javax.swing.Icon icon;
        java.net.URL url = getClass().getResource(address+item2Buy.getItemImage());

        if(url!=null){
            icon = new javax.swing.ImageIcon(url);
        }
        else{
            url = getClass().getResource(address+"null.jpg");
            icon = new javax.swing.ImageIcon(url);
        }
        imageLabel.setIcon(icon);
        NameLabel.setText(item2Buy.getItemName());
        TypeLabel.setText(item2Buy.getItemType());
        PriceLabel.setText(String.format("%8.2f",item2Buy.getItemPrice()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        itemNameLabel = new javax.swing.JLabel();
        itemTypeLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        quantityLabel = new javax.swing.JLabel();
        quantitySpinner = new javax.swing.JSpinner();
        totalLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        NameLabel = new javax.swing.JLabel();
        TypeLabel = new javax.swing.JLabel();
        PriceLabel = new javax.swing.JLabel();
        TotalLabel = new javax.swing.JLabel();
        cashLabel = new javax.swing.JLabel();
        cashField = new javax.swing.JTextField();
        changeLabel = new javax.swing.JLabel();
        ChangeLabel = new javax.swing.JLabel();
        buyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/"+Authenticator.icon)));
        setLocationByPlatform(true);
        setResizable(false);

        itemNameLabel.setText("ITEM NAME:");

        itemTypeLabel.setText("ITEM TYPE:");

        priceLabel.setText("PRICE:");

        quantityLabel.setText("QUANTITY:");

        quantitySpinner.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quantitySpinner.setDoubleBuffered(true);
        quantitySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quantitySpinnerStateChanged(evt);
            }
        });

        totalLabel.setText("TOTAL:");

        NameLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        NameLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        NameLabel.setText("No Item Selected");

        TypeLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        TypeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TypeLabel.setText("No Item Selected");

        PriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        PriceLabel.setText("0.00");

        TotalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        TotalLabel.setText("0.00");

        cashLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        cashLabel.setText("CASH PAYMENT:");

        cashField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        changeLabel.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        changeLabel.setText("CHANGE:");

        ChangeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ChangeLabel.setText("0.00");

        buyButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buyButton.setText("BUY");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cancelButton.setText("Back");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PettaInventory/images/null.jpg"))); // NOI18N
        imageLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(imageLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imageLabel)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cancelButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(changeLabel))
                            .addComponent(cashLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChangeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cashField, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(quantityLabel)
                            .addComponent(itemNameLabel)
                            .addComponent(itemTypeLabel)
                            .addComponent(priceLabel)
                            .addComponent(totalLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(quantitySpinner, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TotalLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                .addComponent(PriceLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(NameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemNameLabel)
                    .addComponent(NameLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(itemTypeLabel)
                    .addComponent(TypeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(PriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel)
                    .addComponent(quantitySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(totalLabel)
                    .addComponent(TotalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cashField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cashLabel))
                        .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cancelButton)
                        .addComponent(changeLabel)
                        .addComponent(ChangeLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        quantitySpinner.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quantitySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quantitySpinnerStateChanged
        double totalPrice;
        qua = (int)quantitySpinner.getValue();
        if(qua>=item2Buy.getItemStock()){
            qua = item2Buy.getItemStock();
            quantitySpinner.setValue(qua);
        }
        totalPrice=item2Buy.getItemPrice()*qua;
        TotalLabel.setText(String.format("%10.2f", totalPrice));
        TotalPrice=totalPrice;
    }//GEN-LAST:event_quantitySpinnerStateChanged

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
        if("BUY".equals(buyButton.getText())){
            String input=cashField.getText();
            try{
            cash= Double.parseDouble(input);
            if(cash>=TotalPrice){
                change=cash-TotalPrice;
                ChangeLabel.setText(String.format("%8.2f",change));
                buyButton.setText("OK");
                int stock = item2Buy.getItemStock() - qua;
                item2Buy.setItemStock(stock);
                PettaInventory.cashier.returner = item2Buy;
                PettaInventory.cashier.updateList();
            }
            else
                javax.swing.JOptionPane.showMessageDialog(null,"Not enough money");
            }catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null,"Please Pay with NUMBERS.");
            }
        }
        else{
            buyButton.setText("BUY");
            TotalPrice=0.0;
            change=0.0;
            TotalLabel.setText(String.format("%10.2f", 0.0));
            ChangeLabel.setText(String.format("%10.2f",0.0));
            quantitySpinner.setValue(0);
            cashField.setText("");
        }
            
    }//GEN-LAST:event_buyButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChangeLabel;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JLabel PriceLabel;
    private javax.swing.JLabel TotalLabel;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JButton buyButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField cashField;
    private javax.swing.JLabel cashLabel;
    private javax.swing.JLabel changeLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel itemNameLabel;
    private javax.swing.JLabel itemTypeLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JSpinner quantitySpinner;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
