/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PettaInventory;

/**
 *
 * @author MasterPaulo
 */
public class EditMenu extends javax.swing.JFrame {
    private InventoryItem item2Edit;
    private InventoryItem defaults;//saves default values to be restored if neccesary
    private javax.swing.ButtonModel defaultRButton;
    public EditMenu() {
        initComponents();
        nameField.setText("");
        priceField.setText("");
        stockField.setText("");
        item2Edit= new InventoryItem();
        item2Edit.setItemNumber(PettaInventory.cashier.numberOfItems);
        item2Edit.setItemQuantity(0);
        
    }

    public EditMenu( InventoryItem item2Edit){
        super("Editing - " + item2Edit.getItemName());
        initComponents();
        nameField.setText(item2Edit.getItemName());
        priceField.setText(String.format("%4.2f",item2Edit.getItemPrice()));
        stockField.setText(String.format("%d",item2Edit.getItemStock()));
        imageField.setText(item2Edit.getItemImage());
        int code =item2Edit.getItemCode();
        defaultRButton = getSelectedButton(code).getModel();
        ItemTypeButtonGroup.setSelected(defaultRButton, rootPaneCheckingEnabled);
        this.item2Edit = defaults = item2Edit;
    }
    public final javax.swing.JRadioButton getSelectedButton(int code){
        javax.swing.JRadioButton finder;
        switch (code){
            case 0: finder = cpuButton;
                    break;
            case 1: finder = ramButton;
                    break;
            case 2: finder = hddButton;
                    break;
            case 3: finder = mainboardButton;
                    break;
            case 4: finder = gcardButton;
                    break;
            case 5: finder = romButton;
                    break;
            case 6: finder = modemButton;
                    break;
            case 7: finder = lancardButton;
                    break;
            case 8: finder = caseButton;
                    break;
            case 9: finder = keyboardButton;
                    break;
            case 10: finder = mouseButton;
                    break;
            case 11: finder = speakersButton;
                    break;
            case 12: finder = monitorButton;
                    break;
            case 13: finder = printerButton;
                    break;
            case 14: finder = scannerButton;
                    break;
            case 15: finder = otherButton;
                    break;
            case 16: finder = otherButton;
                    break;
            default: finder =null;
        }
        return finder;
    }
    
    public boolean Checker(){
        String error = "Please fill-up all fields.";
        if(nameField.getText().isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(null, error);
            return false;
        }
        //if(item2Edit.getItemCode()==){
        //    javax.swing.JOptionPane.showMessageDialog(null, "Please choos a type.");
        //    return false;
        //}
        try{
            Integer.parseInt(stockField.getText());
        }catch(java.lang.NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, error);
            return false;
        }
        
        try{
            Double.parseDouble(priceField.getText());
        }catch(java.lang.NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(null, error);
            return false;
        }
        
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ItemTypeButtonGroup = new javax.swing.ButtonGroup();
        nameLabel = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        priceLabel = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        typePane = new javax.swing.JPanel();
        cpuButton = new javax.swing.JRadioButton();
        ramButton = new javax.swing.JRadioButton();
        hddButton = new javax.swing.JRadioButton();
        mainboardButton = new javax.swing.JRadioButton();
        gcardButton = new javax.swing.JRadioButton();
        romButton = new javax.swing.JRadioButton();
        modemButton = new javax.swing.JRadioButton();
        lancardButton = new javax.swing.JRadioButton();
        caseButton = new javax.swing.JRadioButton();
        keyboardButton = new javax.swing.JRadioButton();
        mouseButton = new javax.swing.JRadioButton();
        speakersButton = new javax.swing.JRadioButton();
        monitorButton = new javax.swing.JRadioButton();
        printerButton = new javax.swing.JRadioButton();
        scannerButton = new javax.swing.JRadioButton();
        otherButton = new javax.swing.JRadioButton();
        priceField = new javax.swing.JTextField();
        stockField = new javax.swing.JTextField();
        imageField = new javax.swing.JTextField();
        defaultButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/"+Authenticator.icon)));

        nameLabel.setText("Item Name:");

        nameField.setText("Name");

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        priceLabel.setText("Item Price:");

        stockLabel.setText("Item Stock:");

        jLabel5.setText("Item Image File:");

        typePane.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Item Type"));

        ItemTypeButtonGroup.add(cpuButton);
        cpuButton.setText("CPU");
        cpuButton.setActionCommand("0");
        cpuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpuButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(ramButton);
        ramButton.setText("RAM");
        ramButton.setActionCommand("1");
        ramButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ramButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(hddButton);
        hddButton.setText("HDD");
        hddButton.setActionCommand("2");
        hddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hddButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(mainboardButton);
        mainboardButton.setText("Main Board");
        mainboardButton.setActionCommand("3");
        mainboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainboardButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(gcardButton);
        gcardButton.setText("Graphics Card");
        gcardButton.setActionCommand("4");
        gcardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gcardButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(romButton);
        romButton.setText("CD/DVD/BD-ROM");
        romButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                romButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(modemButton);
        modemButton.setText("Modem");
        modemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modemButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(lancardButton);
        lancardButton.setText("Lan Card");
        lancardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lancardButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(caseButton);
        caseButton.setText("Case / Chasis");
        caseButton.setActionCommand("8");
        caseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(keyboardButton);
        keyboardButton.setText("Keyboard");
        keyboardButton.setActionCommand("9");
        keyboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keyboardButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(mouseButton);
        mouseButton.setText("Mouse");
        mouseButton.setActionCommand("10");
        mouseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mouseButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(speakersButton);
        speakersButton.setText("Speakers");
        speakersButton.setActionCommand("11");
        speakersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speakersButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(monitorButton);
        monitorButton.setText("Monitor");
        monitorButton.setActionCommand("12");
        monitorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monitorButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(printerButton);
        printerButton.setText("Printer");
        printerButton.setActionCommand("13");
        printerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printerButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(scannerButton);
        scannerButton.setText("Scanner");
        scannerButton.setActionCommand("14");
        scannerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scannerButtonActionPerformed(evt);
            }
        });

        ItemTypeButtonGroup.add(otherButton);
        otherButton.setText("Other Types");
        otherButton.setActionCommand("15");
        otherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                otherButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout typePaneLayout = new javax.swing.GroupLayout(typePane);
        typePane.setLayout(typePaneLayout);
        typePaneLayout.setHorizontalGroup(
            typePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(typePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gcardButton)
                    .addComponent(cpuButton)
                    .addComponent(ramButton)
                    .addComponent(mainboardButton)
                    .addComponent(hddButton)
                    .addComponent(romButton)
                    .addComponent(modemButton)
                    .addComponent(lancardButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(typePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monitorButton)
                    .addComponent(caseButton)
                    .addComponent(keyboardButton)
                    .addComponent(speakersButton)
                    .addComponent(mouseButton)
                    .addComponent(printerButton)
                    .addComponent(scannerButton)
                    .addComponent(otherButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        typePaneLayout.setVerticalGroup(
            typePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(typePaneLayout.createSequentialGroup()
                .addGroup(typePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(typePaneLayout.createSequentialGroup()
                        .addComponent(caseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(keyboardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mouseButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(speakersButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monitorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(printerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scannerButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(otherButton))
                    .addGroup(typePaneLayout.createSequentialGroup()
                        .addComponent(cpuButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ramButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hddButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainboardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gcardButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(romButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(modemButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lancardButton)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        priceField.setText("0.00");

        stockField.setText("0");

        imageField.setText("null.jpg");
        imageField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageFieldActionPerformed(evt);
            }
        });

        defaultButton.setText("Restore Defaults");
        defaultButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(defaultButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(typePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imageField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(stockLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stockField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(priceLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(priceField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nameLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton)
                            .addComponent(cancelButton)
                            .addComponent(defaultButton)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(nameLabel)
                                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(priceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(priceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(stockLabel)
                                    .addComponent(stockField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(imageField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(typePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imageFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imageFieldActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if(Checker()){
        item2Edit.setItemName(nameField.getText()); 
        item2Edit.setItemPrice(Double.parseDouble(priceField.getText()));
        item2Edit.setItemStock(Integer.parseInt(stockField.getText()));
        item2Edit.setItemImage(imageField.getText());
        PettaInventory.cashier.returner=item2Edit;
        PettaInventory.cashier.updateList();
        dispose();
        }
            
    }//GEN-LAST:event_saveButtonActionPerformed

    private void defaultButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultButtonActionPerformed
        nameField.setText(defaults.getItemName());
        priceField.setText(String.format("%4.2f",defaults.getItemPrice()));
        stockField.setText(String.format("%d",defaults.getItemStock()));
        imageField.setText(defaults.getItemImage());
        ItemTypeButtonGroup.setSelected(defaultRButton, rootPaneCheckingEnabled);
    }//GEN-LAST:event_defaultButtonActionPerformed

    private void cpuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpuButtonActionPerformed
        item2Edit.setItemCode(0);
    }//GEN-LAST:event_cpuButtonActionPerformed

    private void ramButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ramButtonActionPerformed
        item2Edit.setItemCode(1);
    }//GEN-LAST:event_ramButtonActionPerformed

    private void hddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hddButtonActionPerformed
        item2Edit.setItemCode(2);
    }//GEN-LAST:event_hddButtonActionPerformed

    private void mainboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainboardButtonActionPerformed
        item2Edit.setItemCode(3);
    }//GEN-LAST:event_mainboardButtonActionPerformed

    private void gcardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gcardButtonActionPerformed
        item2Edit.setItemCode(4);
    }//GEN-LAST:event_gcardButtonActionPerformed

    private void romButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_romButtonActionPerformed
        item2Edit.setItemCode(5);
    }//GEN-LAST:event_romButtonActionPerformed

    private void modemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modemButtonActionPerformed
        item2Edit.setItemCode(6);
    }//GEN-LAST:event_modemButtonActionPerformed

    private void lancardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lancardButtonActionPerformed
        item2Edit.setItemCode(7);
    }//GEN-LAST:event_lancardButtonActionPerformed

    private void caseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseButtonActionPerformed
        item2Edit.setItemCode(8);
    }//GEN-LAST:event_caseButtonActionPerformed

    private void keyboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keyboardButtonActionPerformed
        item2Edit.setItemCode(9);
    }//GEN-LAST:event_keyboardButtonActionPerformed

    private void mouseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mouseButtonActionPerformed
        item2Edit.setItemCode(10);
    }//GEN-LAST:event_mouseButtonActionPerformed

    private void speakersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speakersButtonActionPerformed
        item2Edit.setItemCode(11);
    }//GEN-LAST:event_speakersButtonActionPerformed

    private void monitorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monitorButtonActionPerformed
        item2Edit.setItemCode(12);
    }//GEN-LAST:event_monitorButtonActionPerformed

    private void printerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printerButtonActionPerformed
        item2Edit.setItemCode(13);
    }//GEN-LAST:event_printerButtonActionPerformed

    private void scannerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scannerButtonActionPerformed
        item2Edit.setItemCode(14);
    }//GEN-LAST:event_scannerButtonActionPerformed

    private void otherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_otherButtonActionPerformed
        item2Edit.setItemCode(15);
    }//GEN-LAST:event_otherButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ItemTypeButtonGroup;
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton caseButton;
    private javax.swing.JRadioButton cpuButton;
    private javax.swing.JButton defaultButton;
    private javax.swing.JRadioButton gcardButton;
    private javax.swing.JRadioButton hddButton;
    private javax.swing.JTextField imageField;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton keyboardButton;
    private javax.swing.JRadioButton lancardButton;
    private javax.swing.JRadioButton mainboardButton;
    private javax.swing.JRadioButton modemButton;
    private javax.swing.JRadioButton monitorButton;
    private javax.swing.JRadioButton mouseButton;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JRadioButton otherButton;
    private javax.swing.JTextField priceField;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JRadioButton printerButton;
    private javax.swing.JRadioButton ramButton;
    private javax.swing.JRadioButton romButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JRadioButton scannerButton;
    private javax.swing.JRadioButton speakersButton;
    private javax.swing.JTextField stockField;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JPanel typePane;
    // End of variables declaration//GEN-END:variables
}
