/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PettaInventory;

import java.util.ArrayList;
/**
 *
 * @author Arnel
 */
public class PaymentMenu extends javax.swing.JFrame {
    private double TotalPrice;
    private ArrayList<InventoryItem> items;
    private InventoryItem returner;
    
    private double Cash=0; 
    private double Change=0;
    
    /**
     * Creates new form PaymentMenu
     */
    public PaymentMenu(double total, ArrayList<InventoryItem> items) {
        initComponents();
        totalLabel.setText(String.format("%.2f",total));
        TotalPrice = total;
        this.items = items;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buyButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        changeLabel = new javax.swing.JLabel();
        paymentField = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Purchase");
        setAlwaysOnTop(true);
        setLocationByPlatform(true);
        setResizable(false);

        buyButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buyButton.setText("BUY");
        buyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Total Amount Due:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Enter Payment:");

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Change:");

        changeLabel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        changeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        changeLabel.setText("0.00");

        paymentField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        paymentField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentFieldActionPerformed(evt);
            }
        });

        totalLabel.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        totalLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        totalLabel.setText("0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(buyButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)
                                .addComponent(totalLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paymentField))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3)
                        .addGap(67, 67, 67)
                        .addComponent(changeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(paymentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(changeLabel))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paymentFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentFieldActionPerformed
            
    }//GEN-LAST:event_paymentFieldActionPerformed

    private void buyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyButtonActionPerformed
            if("BUY".equals(buyButton.getText())){
                double cash, change;
                String input = paymentField.getText();
                try{
                Cash = cash=Double.parseDouble(input);
                if(cash>=TotalPrice){
                    Change = change=cash-TotalPrice;
                    changeLabel.setText(String.format("%8.2f",change));
                    buyButton.setText("OK");
                    cancelButton.setText("Receipt");
                    //
                
                }
                else
                    javax.swing.JOptionPane.showMessageDialog(null,"Not enough money");
                }catch(NumberFormatException e){
                javax.swing.JOptionPane.showMessageDialog(null,"Please Pay with NUMBERS.");
                }
            }
            else{
                //prepares to update general list
                for(int i=0 ; i<items.size() ; i++){
                        returner = items.get(i);
                        returner.setItemStock(returner.getItemStock() - returner.getItemQuantity());
                        returner.setItemQuantity(0);
                        PettaInventory.cashier.returner = returner;
                        PettaInventory.cashier.updateList();
                }
                PettaInventory.cashier.carter.dispose();
                PettaInventory.cashier.carter.cart.clear();
                PettaInventory.cashier.carter.updateTable();
                dispose();
            }
            
    }//GEN-LAST:event_buyButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        if("Cancel".equals(cancelButton.getText()))
            dispose();
        else{
            double post[] = {TotalPrice, Cash, Change};
            new RecieptForm(items.toArray(new InventoryItem[items.size()]), post).setVisible(true);
            //prepares to update general list
            for(int i=0 ; i<items.size() ; i++){
                        returner = items.get(i);
                        returner.setItemStock(returner.getItemStock() - returner.getItemQuantity());
                        returner.setItemQuantity(0);
                        PettaInventory.cashier.returner = returner;
                        PettaInventory.cashier.updateList();
            }
            PettaInventory.cashier.carter.dispose();
            PettaInventory.cashier.carter.cart.clear();
            PettaInventory.cashier.carter.updateTable();
            dispose();
        }
    }//GEN-LAST:event_cancelButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buyButton;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel changeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField paymentField;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
