/*
 * PreviewMenu.java
 * show a preview of the item selected
 * ..retrieves image file from give itemIamge name
 */
package PettaInventory;

/**
 *
 * @author MasterPaulo
 */
public class PreviewMenu extends javax.swing.JFrame{
    private InventoryItem item2View;
    
    public PreviewMenu(InventoryItem item2View) {
        super(item2View.getItemName());
        this.item2View = item2View;
        initComponents();
        loadInfo();
    }

    public final void loadInfo(){
        String address = "/PettaInventory/images/";
        if(item2View.getItemCode()==0)
            address+="processors/";
        javax.swing.Icon icon;
        java.net.URL url = getClass().getResource(address+item2View.getItemImage());

        if(url!=null){
            icon = new javax.swing.ImageIcon(url);
        }
        else{
            url = getClass().getResource(address+"null.jpg");
            icon = new javax.swing.ImageIcon(url);
        }
        image.setIcon(icon);
        typeLabel.setText(item2View.getItemType());
        nameLabel.setText(item2View.getItemName());
        priceLabel.setText(String.format("P %4.2f",item2View.getItemPrice()));
        stockLabel.setText(String.format("%d item(s) in stock",item2View.getItemStock()));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        image = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        typeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/"+Authenticator.icon)));
        setLocationByPlatform(true);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PettaInventory/images/null.jpg"))); // NOI18N
        image.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        nameLabel.setText("NAME");
        nameLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        priceLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        priceLabel.setText("PRICE");
        priceLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        stockLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stockLabel.setText("Items In Stock :");
        stockLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        typeLabel.setText("TYPE");
        typeLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(priceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(typeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(image)
                .addGap(7, 7, 7)
                .addComponent(typeLabel)
                .addGap(5, 5, 5)
                .addComponent(nameLabel)
                .addGap(6, 6, 6)
                .addComponent(priceLabel)
                .addGap(6, 6, 6)
                .addComponent(stockLabel)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel image;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JLabel typeLabel;
    // End of variables declaration//GEN-END:variables
}
