/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PettaInventory;

/**
 *
 * @author Pet
 */
public class QuantityMenu extends javax.swing.JFrame {
    InventoryItem adder;
    public static final int MAIN_MENU = 0;
    public static final int CART_MENU = 1;
    /**
     * Creates new form QuantityMenu
     */
    public QuantityMenu(InventoryItem adder, int from) {
        initComponents();
        setLocationRelativeTo(null);
        this.adder = adder;
        int max = adder.getItemStock();
        int qty = adder.getItemQuantity();
        qtyLabel.setText(String.format("(%d)", max-qty));
        if(from==MAIN_MENU)
            qtySpinner.setModel( new javax.swing.SpinnerNumberModel(1,1,max-qty,1));
        else
            qtySpinner.setModel( new javax.swing.SpinnerNumberModel(0,qty*-1,max-qty,1));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        qtySpinner = new javax.swing.JSpinner();
        promptLabel = new javax.swing.JLabel();
        qtyLabel = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Icons/"+Authenticator.icon)));

        okButton.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        cancelButton.setText("Back");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        qtySpinner.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        qtySpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                qtySpinnerStateChanged(evt);
            }
        });
        qtySpinner.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                qtySpinnerKeyPressed(evt);
            }
        });

        promptLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        promptLabel.setText("Enter Quantity:");

        qtyLabel.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        qtyLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        qtyLabel.setText("(0)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(promptLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(qtySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(promptLabel)
                    .addComponent(qtyLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(qtySpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(okButton, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        int qty = (int)qtySpinner.getValue();
        adder.setItemQuantity(qty+adder.getItemQuantity());
        PettaInventory.cashier.carter.addItem(adder);
        dispose();
        
    }//GEN-LAST:event_okButtonActionPerformed

    private void qtySpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_qtySpinnerStateChanged
        int qua = (int)qtySpinner.getValue();
        if(qua>=adder.getItemStock()){
            qua = adder.getItemStock() - adder.getItemQuantity();
            qtySpinner.setValue(qua);
        }
    }//GEN-LAST:event_qtySpinnerStateChanged

    private void qtySpinnerKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_qtySpinnerKeyPressed
        if(evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER){
            int qty = (int)qtySpinner.getValue();
            adder.setItemQuantity(qty+adder.getItemQuantity());
            PettaInventory.cashier.carter.addItem(adder);
            dispose();
        }
    }//GEN-LAST:event_qtySpinnerKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel promptLabel;
    private javax.swing.JLabel qtyLabel;
    private javax.swing.JSpinner qtySpinner;
    // End of variables declaration//GEN-END:variables
}
