/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PettaInventory;

/**
 *
 * @author MasterPaulo
 */
public class RecieptForm extends javax.swing.JFrame {
    private static String date = "Date: " + GetCurrentDateTime.usingDate();
    private static final String header[] = {"                 Petta Inventory©          ",
                                            "                 Bicol University          ",
                                            "                College of Science         ",
                                            "               Computer Science and",
                                            "         Information Technology Department        ",
                                            "                   Legazpi City", " ",
                                            date,
                                            "--------------------------------------------------",
                                            "  Qty   Item                            Subtotal"};
    private static final String footer[] = {"                                          ",
                                            "                                          ",
                                            "        This serves as an official receipt        ",
                                            "         Your feedback is important to us.",
                                            "               Call 09077178075 or",
                                            "            email: pet3175@gmail.com"
                                            };
    
    
    
		
    /**
     * Creates new form RecieptForm
     */
    public RecieptForm(InventoryItem purchase , double []trans) {
        initComponents();
        this.setLocationRelativeTo(null);
        printReceipt(purchase, trans);
    }

     public RecieptForm(InventoryItem []purchases, double []trans) {
        initComponents();
        this.setLocationRelativeTo(null);
        printReceipt(purchases, trans);
    }
     
    public void printReceipt(InventoryItem purchase, double []trans){
        int qty = purchase.getItemQuantity();
        String name = purchase.getItemName();
        double total = purchase.getItemPrice()*qty;
        
        String items[] = {String.format("%4d  %-30s %11.2f", qty, name, total)};
        
        String post[] = new String[4];
        post[0]= "--------------------------------------------------";
        post[1]= String.format(" Total Amount Due: %29.2f ", trans[0]);
        post[2]= String.format(" Cash Tendered:    %29.2f ", trans[1]);
        post[3]= String.format(" Change:           %29.2f ", trans[2]);
        
        
        String []receipt = connect(header , items);
        receipt = connect(receipt, post);
        receipt = connect(receipt, footer);
        list.setListData(receipt);
    }
    
    public void printReceipt(InventoryItem []purchases, double []trans){
        String items[] = new String[purchases.length];
        
        for(int i=0;i<purchases.length;i++){
            int qty = purchases[i].getItemQuantity();
            String name = purchases[i].getItemName();
            double total = purchases[i].getItemPrice()*qty;
        
            items[i] = String.format("%4d  %-30s %11.2f", qty, name, total);
        }
        
        String post[] = new String[4];
        post[0]= "--------------------------------------------------";
        post[1]= String.format(" Total Amount Due: %29.2f ", trans[0]);
        post[2]= String.format(" Cash Tendered:    %29.2f ", trans[1]);
        post[3]= String.format(" Change:           %29.2f ", trans[2]);
        
        
        String []receipt = connect(header , items);
        receipt = connect(receipt, post);
        receipt = connect(receipt, footer);
        list.setListData(receipt);
    }
    public static String[] connect(String[] str1, String[] str2){
        String str[] = new String[str1.length+str2.length];
        int i;
        for(i=0;i<str1.length;i++)
            str[i] = str1[i];
        for(int j=0;j<str2.length;j++,i++)
            str[i]=str2[j];
        return str;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JList();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        list.setFont(new java.awt.Font("Lucida Console", 0, 11)); // NOI18N
        list.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "--------------------------------------------------" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        list.setFocusable(false);
        list.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(list);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList list;
    // End of variables declaration//GEN-END:variables
}
